// Generated by CoffeeScript 1.10.0

/*

 Asset loader
 loads in the assets! maybe I should give it a proper name to reflect its function better...
 */
var load_assets;

load_assets = function(cb) {
  var loader;
  loader = PIXI.loader;
  loader.add('chars', 'img/chars.png');
  loader.add('chars_commodore', 'img/chars-commodore.png');
  loader.add('chars_commodore_green', 'img/chars-commodore-green.png');
  loader.add('chars_commodore_orange', 'img/chars-commodore-orange.png');
  loader.add('chars_hint', 'img/chars-hint.png');
  loader.add('music', 'sound/ghost-town-loop.ogg');
  loader.once('complete', function() {
    return cb();
  });
  loader.load();
};

//# sourceMappingURL=asset-loader.js.map
