// Generated by CoffeeScript 1.10.0
var C16Loader;

C16Loader = (function() {
  function C16Loader() {
    this.kingsoft = new PIXI.Sprite.fromImage('img/kingsoft.png');
    this.credits = new PIXI.Sprite.fromImage('img/credits.png');
    this.display_credits();
  }

  C16Loader.prototype.display_kingsoft = function() {
    display.change_screen_colors("full", COLOR_BLUE, COLOR_BLUE);
    return display.addElement(this.kingsoft);
  };

  C16Loader.prototype.display_credits = function() {
    display.change_screen_colors("full", COLOR_BLACK, COLOR_BLACK);
    return display.addElement(this.credits);
  };

  return C16Loader;

})();

//# sourceMappingURL=C16-loader.js.map
