// Generated by CoffeeScript 1.8.0

/*

  Ghost Town JS - a JavaScript remake of the Commodore C16, C116, Plus/4 game
  Original version written by Udo Gertz, copyright Kingsoft 1985
  Remake written by Ingo Hinterding 2015,2016
 */
var init, init_game;

init = function() {
  load_assets(function() {
    return init_game();
  });
};

init_game = function() {
  var chars_tx;
  document.addEventListener('keydown', event_keydown, false);
  chars_tx = new PIXI.Texture.fromImage('img/chars1.png');
  this.charset = new Generate_charset(chars_tx, 8, 8, 16, 16);
  this.all_levels = new Levels();
  this.room = new Room();
  this.player = new Player();
  this.display = new Display();
  this.display.renderloop();
  return setTimeout((function(_this) {
    return function() {
      return _this.room.set(2);
    };
  })(this), 500);
};

//# sourceMappingURL=main.js.map
