// Generated by CoffeeScript 1.10.0

/*

  Ghost Town JS - a JavaScript remake of the Commodore C16, C116, Plus/4 game
  Original version created by Udo Gertz, copyright Kingsoft 1985
  Remake written by Ingo Hinterding 2015,2016
 */
var init, init_game;

init = function() {
  load_assets(function() {
    return init_game();
  });
};

init_game = function() {
  var chars_commodore_green_tx, chars_commodore_tx, chars_game_tx, chars_hint_tx;
  KeyboardController({
    37: function() {
      player.set_position(37);
    },
    38: function() {
      player.set_position(38);
    },
    39: function() {
      player.set_position(39);
    },
    40: function() {
      player.set_position(40);
    },
    32: function() {
      room.check_spacebar_event();
    }
  }, 60);
  chars_game_tx = new PIXI.Texture.fromImage('img/chars.png');
  this.charset_game = new Generate_charset(chars_game_tx, 8, 8, 16, 16);
  chars_commodore_tx = new PIXI.Texture.fromImage('img/chars-commodore.png');
  this.charset_commodore = new Generate_charset(chars_commodore_tx, 8, 8, 16, 16);
  chars_commodore_green_tx = new PIXI.Texture.fromImage('img/chars-commodore-green.png');
  this.charset_commodore_green = new Generate_charset(chars_commodore_green_tx, 8, 8, 16, 16);
  chars_hint_tx = new PIXI.Texture.fromImage('img/chars-hint.png');
  this.charset_hint = new Generate_charset(chars_hint_tx, 8, 8, 16, 16);
  this.all_lvl = new BinaryImport("lvl");
  this.all_msg = new BinaryImport("msg");
  this.all_other = new BinaryImport("other");
  this.room = new Room();
  this.player = new Player();
  this.display = new Display();
  this.display.renderloop();
  ui_log("Ghost Town JS. Current build: 15.12.17", "green");
  ui_log("User cursor keys to move the player.", "green");
  return setTimeout((function(_this) {
    return function() {
      _this.all_lvl.screen_data_copy = clone(_this.all_lvl.screen_data);
      return _this.room.set(18);
    };
  })(this), 300);
};

//# sourceMappingURL=main.js.map
