// Generated by CoffeeScript 1.9.0

/*
  
  Player
 */
var Player;

Player = (function() {
  function Player() {
    this.position;
    this.inventory = [];
  }

  Player.prototype.get_position = function() {
    return this.position;
  };

  Player.prototype.set_position = function(direction) {
    if (direction === KEY.LEFT && room.check_room(KEY.LEFT)) {
      this.position -= 1;
      room.update(this.position);
    }
    if (direction === KEY.RIGHT && room.check_room(KEY.RIGHT)) {
      this.position += 1;
      room.update(this.position);
    }
    if (direction === KEY.UP && room.check_room(KEY.UP)) {
      this.position -= 40;
      room.update(this.position);
    }
    if (direction === KEY.DOWN && room.check_room(KEY.DOWN)) {
      this.position += 40;
      room.update(this.position);
    }
    console.log("---------");
    console.log(this.position + " : " + (this.position + 3));
    return console.log((this.position + (3 * 40)) + " : " + (this.position + (3 * 40) + 3));
  };

  Player.prototype.add = function(item) {
    this.inventory.push(item);
    ui_inventory(this.inventory);
    return ui_log("You picked up a <b>" + item + "</b>", "green");
  };

  Player.prototype.remove = function(item) {
    this.inventory.splice(this.inventory.indexOf(item), 1);
    return ui_inventory(this.inventory);
  };

  return Player;

})();

//# sourceMappingURL=Player.js.map
