// Generated by CoffeeScript 1.8.0
var Levels;

Levels = (function() {

  /*
  
    GHOST TOWN JS
    LEVEL GENERATOR
   */
  function Levels() {
    var i;
    this.screen_data = [];
    this.level_data = levels_config;
    i = 0;
    while (i < 20) {
      i++;
      this.screen_data[i] = this.import_screen_data(this.level_data[i].filename);
    }
  }

  Levels.prototype.import_screen_data = function(filename) {
    var file_fullpath, oReq, screendat;
    file_fullpath = 'data/screen-lvl-' + filename + '.bin';
    screendat = [];
    oReq = new XMLHttpRequest;
    oReq.open('GET', file_fullpath, true);
    oReq.responseType = 'arraybuffer';
    oReq.onload = function(oEvent) {
      var arrayBuffer, byteArray, char, i;
      arrayBuffer = oReq.response;
      if (arrayBuffer) {
        byteArray = new Uint8Array(arrayBuffer);
        i = 2;
        while (i < byteArray.byteLength) {
          char = ('0' + byteArray[i].toString(16)).slice(-2);
          screendat.push(char);
          i++;
        }
      }
    };
    oReq.send(null);
    return screendat;
  };

  return Levels;

})();

//# sourceMappingURL=Levels.js.map
