// Generated by CoffeeScript 1.8.0

/*

  Ghost Town JS - a JavaScript remake of the Commodore C16, C116, Plus/4 game
  Original version written by Udo Gertz, copyright Kingsoft 1985
  Remake written by Ingo Hinterding 2015,2016
 */
var asset_loader_ready, init, init_game;

init = function() {
  log('<b>Welcome to Ghost Town JS.</b>', 'green');
  load_assets();
};

asset_loader_ready = function() {
  log('assets loaded.');
  init_game();
};

init_game = function() {
  var chars_tx;
  this.display = new Display();
  chars_tx = new PIXI.Texture.fromImage('img/chars1.png');
  this.charset = new Generate_charset(chars_tx, 8, 8, 16, 16).all_chars;
  this.all_levels = new Levels();
  return this.display.renderloop();
};

//# sourceMappingURL=main.js.map
