// Generated by CoffeeScript 1.9.0
var levels_config;

levels_config = {
  1: {
    filename: '01',
    name: 'start',
    oranges: 4
  },
  2: {
    filename: '02',
    name: 'Wirecutter',
    oranges: 4
  },
  3: {
    filename: '03',
    name: 'The ladder',
    oranges: 4
  },
  4: {
    filename: '04',
    name: '',
    oranges: 4
  },
  5: {
    filename: '05',
    name: '',
    oranges: 4
  },
  6: {
    filename: '06',
    name: '',
    oranges: 4
  },
  7: {
    filename: '07',
    name: '',
    oranges: 4
  },
  8: {
    filename: '08',
    name: '',
    oranges: 4
  },
  9: {
    filename: '09',
    name: '',
    oranges: 4
  },
  10: {
    filename: '10',
    name: '',
    oranges: 4
  },
  11: {
    filename: '11',
    name: '',
    oranges: 4
  },
  12: {
    filename: '12',
    name: '',
    oranges: 4
  },
  13: {
    filename: '13',
    name: '',
    oranges: 4
  },
  14: {
    filename: '14',
    name: '',
    oranges: 4
  },
  15: {
    filename: '15',
    name: '',
    oranges: 4
  },
  16: {
    filename: '16',
    name: '',
    oranges: 4
  },
  17: {
    filename: '17',
    name: '',
    oranges: 4
  },
  18: {
    filename: '18',
    name: '',
    oranges: 4
  },
  19: {
    filename: '19',
    name: '',
    oranges: 4
  },
  20: {
    filename: '20',
    name: '',
    oranges: 4
  }
};
