// Generated by CoffeeScript 1.9.0

/*
  
  display manager
 */
var Display;

Display = (function() {
  function Display() {}

  Display.prototype.show_level = function(level) {
    var i, level_data, level_sprites, xpos, ypos, _results;
    log("Level: " + level, 1);
    level_sprites = [];
    xpos = 0;
    ypos = 0;
    level_data = all_levels.screens[level];
    this.clear();
    i = 0;
    _results = [];
    while (i < level_data.length) {
      level_sprites[i] = new PIXI.Sprite(charset[level_data[i]]);
      if (xpos >= SCREEN_WIDTH) {
        xpos = 0;
        ypos += 8;
      }
      level_sprites[i].position.x = xpos;
      level_sprites[i].position.y = ypos;
      screen.addChild(level_sprites[i]);
      xpos += 8;
      _results.push(i++);
    }
    return _results;
  };

  Display.prototype.clear = function() {
    var i;
    i = screen.children.length - 1;
    while (i >= 0) {
      screen.removeChild(screen.children[i]);
      i--;
    }
    return screen.addChild(bg);
  };

  return Display;

})();

//# sourceMappingURL=Display.js.map
