// Generated by CoffeeScript 1.8.0
var levels_config;

levels_config = {
  1: {
    filename: '01',
    name: 'The journey begins',
    playerpos1: 243,
    playerpos2: 753
  },
  2: {
    filename: '02',
    name: 'Now you see me...',
    playerpos1: 123,
    playerpos2: 753
  },
  3: {
    filename: '03',
    name: 'The ladder',
    playerpos1: 123,
    playerpos2: 873
  },
  4: {
    filename: '04',
    name: 'The tedious way',
    playerpos1: 123,
    playerpos2: 633
  },
  5: {
    filename: '05',
    name: 'I smell dead people',
    playerpos1: 870,
    playerpos2: 246
  },
  6: {
    filename: '06',
    name: 'Boulder Trash',
    playerpos1: 243,
    playerpos2: 753
  },
  7: {
    filename: '07',
    name: '4 Rooms 3 deaths',
    playerpos1: 123,
    playerpos2: 393
  },
  8: {
    filename: '08',
    name: 'The Graveyard',
    playerpos1: 123,
    playerpos2: 753
  },
  9: {
    filename: '09',
    name: 'Klondyke',
    playerpos1: 123,
    playerpos2: 513
  },
  10: {
    filename: '10',
    name: 'Boris the Spider',
    playerpos1: 123,
    playerpos2: 753
  },
  11: {
    filename: '11',
    name: 'BRRRZ!!!!',
    playerpos1: 483,
    playerpos2: 513
  },
  12: {
    filename: '12',
    name: 'Hammer in the Woods',
    playerpos1: 483,
    playerpos2: 513,
    objects: ["hammer"]
  },
  13: {
    filename: '13',
    name: 'Center Door',
    playerpos1: 483,
    playerpos2: 375
  },
  14: {
    filename: '14',
    name: 'Yikes! Spikes!',
    playerpos1: 123,
    playerpos2: 273
  },
  15: {
    filename: '15',
    name: '..and now this.',
    playerpos1: 123,
    playerpos2: 153
  },
  16: {
    filename: '16',
    name: 'Skeleton Fashion',
    playerpos1: 243,
    playerpos2: 753
  },
  17: {
    filename: '17',
    name: 'The Prison',
    playerpos1: 123,
    playerpos2: 101
  },
  18: {
    filename: '18',
    name: 'Belegro',
    playerpos1: 123,
    playerpos2: 273
  },
  19: {
    filename: '19',
    name: 'Almost there!',
    playerpos1: 123,
    playerpos2: 88
  }
};

//# sourceMappingURL=config-levels.js.map
