// Generated by CoffeeScript 1.10.0
var levels_config;

levels_config = {
  1: {
    name: 'The journey begins',
    playerpos1: 243,
    playerpos2: 753
  },
  2: {
    name: 'Now you see me...',
    playerpos1: 123,
    playerpos2: 753
  },
  3: {
    name: 'The ladder',
    playerpos1: 123,
    playerpos2: 873
  },
  4: {
    name: 'The tedious way',
    playerpos1: 123,
    playerpos2: 633
  },
  5: {
    name: 'I smell dead people',
    playerpos1: 870,
    playerpos2: 246
  },
  6: {
    name: 'Boulder Trash',
    playerpos1: 243,
    playerpos2: 753
  },
  7: {
    name: '4 Rooms 3 deaths',
    playerpos1: 123,
    playerpos2: 393
  },
  8: {
    name: 'The Graveyard',
    playerpos1: 123,
    playerpos2: 753
  },
  9: {
    name: 'Klondyke',
    playerpos1: 123,
    playerpos2: 513
  },
  10: {
    name: 'Boris the Spider',
    playerpos1: 123,
    playerpos2: 753
  },
  11: {
    name: 'BRRRZ!!!!',
    playerpos1: 483,
    playerpos2: 513
  },
  12: {
    name: 'Hammer in the Woods',
    playerpos1: 483,
    playerpos2: 513
  },
  13: {
    name: 'Center Door',
    playerpos1: 483,
    playerpos2: 375
  },
  14: {
    name: 'Yikes! Spikes!',
    playerpos1: 123,
    playerpos2: 273
  },
  15: {
    name: '..and now this.',
    playerpos1: 123,
    playerpos2: 153
  },
  16: {
    name: 'Skeleton Fashion',
    playerpos1: 243,
    playerpos2: 753
  },
  17: {
    name: 'The Prison',
    playerpos1: 123,
    playerpos2: 149
  },
  18: {
    name: 'Belegro',
    playerpos1: 123,
    playerpos2: 273
  },
  19: {
    name: 'Almost there!',
    playerpos1: 123,
    playerpos2: 88
  }
};

//# sourceMappingURL=config-levels.js.map
